/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.constantine

import com.constantine.step.ReqresSteps
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class ReqresTests {

    private val reqresSteps = ReqresSteps("https://reqres.in/")

    @Test
    fun testAppHasAGreeting() {
        val response = reqresSteps.listUsers(1, 6)
        assertTrue(response.isSuccessful, "Request wasn't successful")
    }
}
